//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.BusinessEntities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/Blog.BusinessEntities")]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CreateDateField;
        
        private System.Guid IdField;
        
        private Blog.BusinessEntities.BlogPost PostField;
        
        private string TextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Blog.BusinessEntities.BlogPost Post
        {
            get
            {
                return this.PostField;
            }
            set
            {
                this.PostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogPost", Namespace="http://schemas.datacontract.org/2004/07/Blog.BusinessEntities")]
    public partial class BlogPost : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Blog.BusinessEntities.Comment[] CommentsField;
        
        private System.DateTime CreateDateField;
        
        private string DescriptionField;
        
        private System.Guid IdField;
        
        private string TextField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Blog.BusinessEntities.Comment[] Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBlogService")]
public interface IBlogService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/AddComment", ReplyAction="http://tempuri.org/IBlogService/AddCommentResponse")]
    void AddComment(Blog.BusinessEntities.Comment comment);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/AddComment", ReplyAction="http://tempuri.org/IBlogService/AddCommentResponse")]
    System.Threading.Tasks.Task AddCommentAsync(Blog.BusinessEntities.Comment comment);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/AddPost", ReplyAction="http://tempuri.org/IBlogService/AddPostResponse")]
    void AddPost(Blog.BusinessEntities.BlogPost post);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/AddPost", ReplyAction="http://tempuri.org/IBlogService/AddPostResponse")]
    System.Threading.Tasks.Task AddPostAsync(Blog.BusinessEntities.BlogPost post);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/DeletePost", ReplyAction="http://tempuri.org/IBlogService/DeletePostResponse")]
    void DeletePost(Blog.BusinessEntities.BlogPost post);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/DeletePost", ReplyAction="http://tempuri.org/IBlogService/DeletePostResponse")]
    System.Threading.Tasks.Task DeletePostAsync(Blog.BusinessEntities.BlogPost post);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/GetPost", ReplyAction="http://tempuri.org/IBlogService/GetPostResponse")]
    Blog.BusinessEntities.BlogPost GetPost(System.Guid postId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/GetPost", ReplyAction="http://tempuri.org/IBlogService/GetPostResponse")]
    System.Threading.Tasks.Task<Blog.BusinessEntities.BlogPost> GetPostAsync(System.Guid postId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/GetPosts", ReplyAction="http://tempuri.org/IBlogService/GetPostsResponse")]
    Blog.BusinessEntities.BlogPost[] GetPosts();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/GetPosts", ReplyAction="http://tempuri.org/IBlogService/GetPostsResponse")]
    System.Threading.Tasks.Task<Blog.BusinessEntities.BlogPost[]> GetPostsAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBlogServiceChannel : IBlogService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BlogServiceClient : System.ServiceModel.ClientBase<IBlogService>, IBlogService
{
    
    public BlogServiceClient()
    {
    }
    
    public BlogServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BlogServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BlogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BlogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddComment(Blog.BusinessEntities.Comment comment)
    {
        base.Channel.AddComment(comment);
    }
    
    public System.Threading.Tasks.Task AddCommentAsync(Blog.BusinessEntities.Comment comment)
    {
        return base.Channel.AddCommentAsync(comment);
    }
    
    public void AddPost(Blog.BusinessEntities.BlogPost post)
    {
        base.Channel.AddPost(post);
    }
    
    public System.Threading.Tasks.Task AddPostAsync(Blog.BusinessEntities.BlogPost post)
    {
        return base.Channel.AddPostAsync(post);
    }
    
    public void DeletePost(Blog.BusinessEntities.BlogPost post)
    {
        base.Channel.DeletePost(post);
    }
    
    public System.Threading.Tasks.Task DeletePostAsync(Blog.BusinessEntities.BlogPost post)
    {
        return base.Channel.DeletePostAsync(post);
    }
    
    public Blog.BusinessEntities.BlogPost GetPost(System.Guid postId)
    {
        return base.Channel.GetPost(postId);
    }
    
    public System.Threading.Tasks.Task<Blog.BusinessEntities.BlogPost> GetPostAsync(System.Guid postId)
    {
        return base.Channel.GetPostAsync(postId);
    }
    
    public Blog.BusinessEntities.BlogPost[] GetPosts()
    {
        return base.Channel.GetPosts();
    }
    
    public System.Threading.Tasks.Task<Blog.BusinessEntities.BlogPost[]> GetPostsAsync()
    {
        return base.Channel.GetPostsAsync();
    }
}
